export const PATH_NAME = {
  ROOT: '/',
  ERROR_404: '*',
  LOGIN: 'login',
  REGISTER: 'register',
  FORGOT: 'forgot',
  DASHBOARD: 'dashboard',
  UPDATE_PROFILE: 'update-profile',
  CHAT_OVERVIEW: 'chat',
  CHAT_WINDOW: ':roomId',
  LANDING: 'landing',
  USER_INFOR: 'userinfor/:id',
  CONTACT: 'contact',
  CHANGE_PASSWORD: 'change-password',
  TEST: 'test',
};
